name = "GroundwaterPlots"
uuid = "4497dbff-a3fd-4ae5-909f-dd1339757ac3"
authors = ["monty <velimir.vesselinov@gmail.com>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DocumentFunction = "e1f3b4f0-2dc4-57d3-83f7-d4b7faf3b05b"
Kriging = "6133562b-a8e8-5ea3-954b-37642b766dad"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
ReusableFunctions = "afbf81f7-602f-5a4a-9a77-738a1b1188fe"

[compat]
Colors = "0.12, 0.13"
DocumentFunction = "1"
Kriging = "1"
PyCall = "1"
PyPlot = "2"
ReusableFunctions = "1"
julia = "1.5, 1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]